<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SsmsSqlFormatter.Cli</RootNamespace>
    <AssemblyName>ssmssqlfmt</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SsmsSqlFormatter\SsmsSqlFormatter.csproj" />
  </ItemGroup>

</Project>
